import Head from "next/head";

import FilmList from "@/components/FilmsList";
import Pagination from "@/components/Pagination";
import NotFoundMsg from "@/components/NotFoundMsg";

import { getFilmsByTitle } from "services/films.services";

export default function FilmsList({
  films,
  page,
  totalResults,
  searchStatus,
  serverStatus,
}) {
  return (
    <>
      <Head>
        <title>films</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        {serverStatus ? (
          searchStatus ? (
            <>
              <FilmList films={films.Search} />
              <Pagination currentPage={page} totalResults={totalResults} />{" "}
            </>
          ) : (
            <NotFoundMsg message="We did not find any movies for this request. Please try again.." />
          )
        ) : (
          <div className="container">
            <p>
              Oops, we have a problem with the request. Please try again later.
            </p>
          </div>
        )}
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const { title, page } = context?.query;

  try {
    const films = await getFilmsByTitle(title, page);
    const totalResults = Math.floor(films.totalResults / 10);
    const isRespSuccessful = films.Response === "True" ? true : false;

    return {
      props: {
        films,
        page,
        totalResults,
        searchStatus: isRespSuccessful,
        serverStatus: true,
      },
    };
  } catch (error) {
    return {
      props: { serverRespStatus: false },
    };
  }
}
